=== MichaelSpr/wisbada/backend/docs/stammbaum.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="familie">
      <xs:complexType>
        <xs:sequence>
          <xs:element name ="personen">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="person" maxOccurs="unbounded" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="name" type="xs:string"/>
                      <xs:element name="vorname" type="xs:string"/>
                      <xs:element name="geburtsort" type="xs:string"/>
                      <xs:element name="geburtsdatum" type="xs:date"/>
                      <xs:element name="sterbeort" type="xs:string"/>
                      <xs:element name="todesdatum" type="xs:date" nillable="true"/>
                      <xs:element name="geschlecht">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="m|w" />
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                      <xs:element name="bild" type="xs:string"/>
                      <xs:element name="sonstiges" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:positiveInteger"></xs:attribute>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="beziehungen" >
            <xs:complexType>
              <xs:sequence>
                <xs:element name="partner"  maxOccurs="unbounded" minOccurs="0">
                  <xs:complexType>
                    <xs:attribute name="id" type="xs:positiveInteger"/>
                    <xs:attribute name="partnerEins" type="xs:positiveInteger"/>
                    <xs:attribute name="partnerZwei" type="xs:positiveInteger"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="kind"  maxOccurs="unbounded" minOccurs="0">
                  <xs:complexType>
                    <xs:attribute name="id" type="xs:positiveInteger"/>
                    <xs:attribute name="elternteil" type="xs:positiveInteger"/>
                    <xs:attribute name="kind" type="xs:positiveInteger"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
		  <xs:element name="startat" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:positiveInteger"/>
                    </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="token" type="xs:positiveInteger"></xs:attribute>
      </xs:complexType>
      <xs:unique name="PersonenID">
        <xs:selector xpath="personen/person"/>
        <xs:field xpath="@id"/>
      </xs:unique>
      <xs:unique name="BeziehungsID">
        <xs:selector xpath="beziehungen/*"/>
        <xs:field xpath="@id"/>
      </xs:unique>
      <xs:unique name="BeziehungsPartnerID">
        <xs:selector xpath="beziehungen/*"/>
        <xs:field xpath="@elternteil"/>
        <xs:field xpath="@kind"/>
      </xs:unique>
    </xs:element>
  </xs:schema>

=== MichaelSpr/wisbada/testPage.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="www/html.xsl" type="text/xsl"?>
<familie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" token="1" xsi:noNamespaceSchemaLocation="backend/docs/stammbaum.xsd">
    <personen>
        <person id="1">
            <name>Simpson</name>
            <vorname>Homer Jay</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum>1900-01-01</todesdatum>
            <geschlecht>m</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
        <person id="2">
            <name>Simpson</name>
            <vorname>Marjorie "Marge"</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum>1900-01-01</todesdatum>
            <geschlecht>w</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
        <person id="3">
            <name>Simpson</name>
            <vorname>Bartholomew JoJo "Bart"</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum>1900-01-01</todesdatum>
            <geschlecht>m</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
    </personen>
    <beziehungen>
        <partner id="1" partnerEins="1" partnerZwei="2"/>
        <kind id="2" elternteil="1" kind="3"/>
        <kind id="3" elternteil="2" kind="3"/>
    </beziehungen>
	<startat id="1" />
</familie>

=== MichaelSpr/wisbada/backend/docs/example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<familie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" token="1" xsi:noNamespaceSchemaLocation="stammbaum.xsd">
    <personen>
        <person id="1">
            <name>Simpson</name>
            <vorname>Homer Jay</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
            <geschlecht>m</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
        <person id="2">
            <name>Simpson</name>
            <vorname>Marjorie "Marge"</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
            <geschlecht>w</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
        <person id="3">
            <name>Simpson</name>
            <vorname>Bartholomew JoJo "Bart"</vorname>
            <geburtsort>Springfield</geburtsort>
            <geburtsdatum>1989-12-17</geburtsdatum>
            <sterbeort></sterbeort>
            <todesdatum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
            <geschlecht>m</geschlecht>
            <bild/>
            <sonstiges/>
        </person>
    </personen>
    <beziehungen>
        <partner id="1" partnerEins="1" partnerZwei="2"/>
        <kind id="2" elternteil="1" kind="3"/>
        <kind id="3" elternteil="2" kind="3"/>
    </beziehungen>
</familie>
